### ISSUE TITLE
Makefile suggestions

### ISSUE THREAD

**Issue by kdiverson** [SchlossLab/new_project#2]
These are a few lines I like to add to the top of my makefiles, perhaps they could be included in the default makefile

MAKEFLAGS += --warn-undefined-variables
SHELL := bash
.SHELLFLAGS := -eu -o pipefail

**Comment by pschloss** [comment]
Thanks! what do they do?

**Comment by kdiverson** [comment]
Right, a description would be helpful...`MAKEFLAGS += --warn-undefined-variables` pretty much catches misspelled variables. I like to make use of lots of variables in makefiles so this helps catch typos. Setting the shell to bash `SHELL := bash` allows for SHELLFLAGS to be used. I also use a bit of bash specific syntax so forcing the shell to be bash allows for that. I like the pipefail option because that forces make to stop when something on the left of a pipe is bad but the right side is good since by default only the return value of the last command is returned. Without this make would think this succeeded: `awk '{print $1}' not/a/file.txt | wc -l` because the word count command would have run successfully even though the awk command was bad.
